name: Maven + NodeJS Manual Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install JAM globally
        run: npm install -g jamjs

      - name: Verify JAM installation
        run: jam --version

      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with Maven (debug)
        run: mvn clean install -e -X

      - name: Upload Java Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: java-artifacts
          path: target/*.jar

      - name: Upload Frontend Assets
        uses: actions/upload-artifact@v4
        with:
          name: frontend-assets
          path: |
            src/main/webapp/resources/js/**/*.js
            src/main/webapp/resources/css/**/*.css
