name: Maven Build Node

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build 
        run: mvn clean install -DskipTests -Dskip.jam=true -Dexec.skip=true

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: maven-artifact
          path: target/*.jar
